config/routes.rb
Rails.application.routes.draw do

  resources :locations
  resources :events 
  resources :tasks
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  
  resources :users do
    member { patch :activate }
    member { patch :deactivate }
  end
  
  

  root 'welcome#index'
  get "about_us", to: "welcome#about_us"
  get "contact_us", to: "welcome#contact_us"
  get "weather_forcast", to: "welcome#weather_forcast"


end

app/models/event.rb
class Event < ApplicationRecord
	validates :title, :description, presence: true,
	                                     length: { minimum: 5 }
	validates :avatar, presence: true
	mount_uploader :avatar, AvatarUploader
	has_many :locations, inverse_of: :event
	accepts_nested_attributes_for :locations, allow_destroy: true, reject_if: :all_blank
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  
  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end


private
# Use callbacks to share common setup or 4.2 JSON parameters
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.fetch(:event, {}).permit(:id, :title, :description, :avatar)
  end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="form">
 
<%= form_with model: @event, local: true do |f| %>

  
 <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@event.errors.count, "error") %> prohibited
        this event from being saved:
      </h2>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div> 

  <% end %>

  
  <%= f.hidden_field :event_id, value: @event.id %>   
  
  <div>
  <i class="fas fa-info"></i>


  </div>
  
  
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <br>
  
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <br>

  <div>
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>
   
  
  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/events/_location_fields.html.erb
<%
=begin%>
 <div class="nested-fields">
    <%= f.hidden_field :_destroy %>
   
    <div>
        <%= f.label :place %>
        <%= f.text_field :location %>
    </div>

</div>

 
<%
=end%>








<%
=begin%>
 
    <%= f.hidden_field :_destroy %>
    
    <div>
        <%= f.label :Place %>
        <%= f.text_field :Place %>
    </div> 
<%
=end%>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<h1>Events</h1>

<%= link_to 'Create a New Event', new_event_path %>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <table class="table">
    
  <tr>
    <th>Title</th>
    <th>Description</th> <br>
    <th colspan="2"></th>
  </tr>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td> 
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event_path(event),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<br>
<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<br>
<br>
<br>

<div class="container">
  <%= image_tag(@event.avatar.url, size: '200', alt: 'Image') if @event.avatar? %> <h1>
</div>

<br>
<br>
<br>

<h2>
  <strong>title:</strong>
  <%= @event.title %>
</h2>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>location:</strong>
  <%= @event.location %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>