config/routes.rb
Rails.application.routes.draw do

  resources :locations
  resources :events 
  resources :tasks
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  
  resources :users do
    member { patch :activate }
    member { patch :deactivate }
  end
  
  

  root 'welcome#index'
  get "about_us", to: "welcome#about_us"
  get "contact_us", to: "welcome#contact_us"
  get "weather_forcast", to: "welcome#weather_forcast"


end

app/models/location.rb
class Location < ApplicationRecord
    belongs_to :events
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /locations or /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1 or /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations or /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: "Location was successfully created." }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: "Location was successfully updated." }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: "Location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.fetch(:location, {}).permit(location_attributes: [:id, :address, :city, :state, :country])
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<div class="form">
 
<%= form_with model: @locations, local: true do |f| %>

  
 <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@location.errors.count, "error") %> prohibited
        this location from being saved:
      </h2>
      <ul>
        <% @location.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div> 

  <% end %>

  
  <%= f.hidden_field :location_id, value: @location.id %>   
  
  <div>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>

  <br>
  
  <div>
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>

  <br>

  <div>
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>

  <div>
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div> 
  
  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>