config/routes.rb
Rails.application.routes.draw do

  resources :locations
  resources :events 
  resources :tasks
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  
  resources :users do
    member { patch :activate }
    member { patch :deactivate }
  end
  
  

  root 'welcome#index'
  get "about_us", to: "welcome#about_us"
  get "contact_us", to: "welcome#contact_us"
  get "weather_forcast", to: "welcome#weather_forcast"


end

app/views/layouts/_footer.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">

<style>
.footer {
   position: fixed;
   left: 0;
   bottom: 0;
   width: 100%;
   background-color: #262626;
   color: #bebebe;
   text-align: center;
   background: transparent
}

</style>

</head>
  <body>

  <div class="footer">
    <p>A Event Management Plateform</p> 
    <a href="https://www.gmail.com/"> &#x1F4E8 Contact Us.!</a>
  </div>

</body>
</html> 

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {box-sizing: border-box;}

body { 
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.header {
  overflow: hidden;
  background-color: #282828;
  padding: 20px 10px;
  
}

.header a {
  float: left;
  color: white;
  text-align: center;
  padding: 12px;
  text-decoration: none;
  font-size: 15px; 
  line-height: 25px;
  border-radius: 4px;
}

.header a.logo {
  font-size: 25px;
  font-weight: bold;
  font-family: bold;
}

.header a:hover {
  background-color: #ddd;
  color: black;<%= link_to 'new user', new_user_registration_path %>
}

.header-right {
  float: right;
}

@media screen and (max-width: 500px) {
  .header a {
    float: none;
    display: block;
    text-align: left;
  }
  
  .header-right {
    float: none;
  }
}
</style>
</head>
<body>

<div class="header">
  <a href="http://localhost:3000/" class="logo"> |DREAM&#128508EVENTS| </a> 
  <div class="header-left">
    <%= link_to 'Create a New Event', new_event_path %>
    <%= link_to 'Users', users_path %>
    <%= link_to 'Events', events_path %>
    <%= link_to 'Locations', locations_path %>
    <%= link_to 'About Us', about_us_path %>
    <%= link_to 'Contact Us', contact_us_path %>
    <%= link_to 'Sign in', new_user_session_path %>
    <%= link_to 'Sign up', new_user_registration_path %>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>  
    <%= link_to 'Weather', weather_forcast_path %>
  </div>
</div>


<div style="padding-left:20px">
</div>

</body>
</html>

app/views/layouts/application.html.erb
<%= render 'layouts/navbar' %>
<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>rails-n-bootstrap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>


<%
=begin%>
 <%= link_to 'New Event', new_event_path %> 
<%
=end%>

<%
=begin%>
 #successfuly updated, created, deleted msgs |alerts| 
<%
=end%>
<%= yield %>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


<%= render 'layouts/footer' %>